import pyfibers
from neuron import h, load_mechanisms
import os
import numpy as np
from pyfibers import build_fiber, FiberModel, ScaledStim
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# create fiber model
n_nodes = 25
fiber = build_fiber(FiberModel.MRG_INTERPOLATION, diameter=10, n_nodes=n_nodes)

# Setup for simulation
time_step = 0.001
time_stop = 10
start, on, off = 0, 0.1, 0.2
waveform = interp1d(
    [start, on, off, time_stop], [0, 1, 0, 0], kind="previous"
)  # biphasic rectangular pulse

fiber.potentials = fiber.point_source_potentials(0, 250, fiber.length / 2, 1, 10)

# Create stimulation object
stimulation = ScaledStim(waveform=waveform, dt=time_step, tstop=time_stop)
fiber.record_vm()

fiber.record_im(
    allsec=True
)  # save membrane currents for all sections (default is nodes only)
fiber.record_vext()  # save periaxonal potentials
ap, time = stimulation.run_sim(-1.5, fiber)

x = 0
y = 100  # place electrode 100 um above the fiber
z = 0.9 * fiber.length  # place electrode 90% along the fiber
current = 1  # mA, unit stimulus
sigma = 1  # S/m, extracellular conductivity

# calculate the potentials generated by a point source at the electrode location
recording_potentials = fiber.point_source_potentials(x, y, z, current, sigma)
plt.figure()
plt.plot(fiber.longitudinal_coordinates, recording_potentials)
plt.xlabel('Distance along fiber (um)')
plt.ylabel('Electric potential (mV)')
plt.show()

downsample = 1  # factor by which to downsample recording time
sfap, downsampled_time = fiber.record_sfap(
    recording_potentials, downsample=downsample
)  # record the single fiber action potential

plt.figure()
plt.plot(downsampled_time, sfap, color='black')
plt.xlim(0, 2)
plt.xlabel('Time (ms)')
plt.ylabel('Recorded signal (uV)', color='black')
# plot transmembrane voltage on second axis
plt.twinx()
plt.gca().yaxis.grid(False)
plt.plot(
    stimulation.time,
    np.array(fiber.vm[fiber.loc_index(0.9)]),
    color='red',
    linestyle='--',
)
plt.ylabel('Transmembrane potential (mV)', color='red')
plt.show()

rec_potentials = np.zeros(len(fiber.sections))
for loc, weight in zip([0.89, 0.91], [-1, 1]):
    rec_potentials += (
        fiber.point_source_potentials(x, y, loc * fiber.length, current, sigma) * weight
    )
sfap, downsampled_time = fiber.record_sfap(
    rec_potentials, downsample=downsample
)  # record the single fiber action potential

plt.figure()
plt.plot(np.array(stimulation.time)[::downsample], sfap, color='black')
plt.xlim(0, 2)
plt.xlabel('Time (ms)')
plt.ylabel('Recorded signal (uV)', color='black')
# plot transmembrane voltage on second axis
plt.twinx()
plt.plot(
    stimulation.time,
    np.array(fiber.vm[fiber.loc_index(0.9)]),
    color='red',
    linestyle='--',
)
plt.ylabel('Transmembrane potential (mV)', color='red')
plt.gca().yaxis.grid(False)
plt.show()

fibers = [
    build_fiber(FiberModel.MRG_INTERPOLATION, diameter=d, n_nodes=n_nodes)
    for d in [8, 9, 10]
]
sfaps = []
for fib in fibers:
    fib.record_im(allsec=True)
    fib.record_vext()
    fib.potentials = fib.point_source_potentials(0, 250, fib.length / 2, 1, 10)
    stimulation.run_sim(-1.5, fib)
    recording_potentials = fib.point_source_potentials(x, y, z, current, sigma)
    sfaps.append(fib.record_sfap(recording_potentials, downsample=downsample)[0])

sfap = np.sum(sfaps, axis=0)

plt.figure()
plt.plot(np.array(stimulation.time)[::downsample], sfap, color='black')
plt.xlim(0, 2)
plt.xlabel('Time (ms)')
plt.ylabel('Recorded signal (uV)', color='black')
plt.show()